# Generated by Django 5.2.17 on 2026-09-11 08:19

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='LibrarySetting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('borrow_period_days', models.PositiveIntegerField(default=7, help_text='Default borrowing period in days')),
                ('fine_per_day', models.DecimalField(decimal_places=2, default=Decimal('10.00'), help_text='Fine per late day in ₹', max_digits=8)),
                ('library_name', models.CharField(default='Library Management System', max_length=255)),
                ('contact_email', models.EmailField(default='library@institution.edu', max_length=254)),
                ('contact_phone', models.CharField(default='+91 98765 43210', max_length=20)),
                ('address', models.TextField(default='Central Campus Library, Block A')),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
