# Generated by Django 5.2.17 on 2026-09-11 08:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
        ('books', '0001_initial'),
        ('borrowing', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Receipt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('receipt_id', models.CharField(db_index=True, max_length=30, unique=True)),
                ('receipt_type', models.CharField(choices=[('BORROW', 'BOOK BORROW RECEIPT'), ('RETURN', 'RETURN RECEIPT')], max_length=10)),
                ('data', models.JSONField(default=dict, help_text='Immutable snapshot of receipt details')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='receipts', to='books.book')),
                ('borrow', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='receipts', to='borrowing.borrowrecord')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='receipts', to='accounts.studentprofile')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
